---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install NRPE and basic plugins
  ansible.builtin.package:
      name:
          - nagios-nrpe-server
          - monitoring-plugins-basic
      state: present

- name: Make NRPE start with system
  ansible.builtin.service:
      name: nagios-nrpe-server
      state: started
      enabled: true

# --------------------------------------------------
# CONFIGURATION NRPE
# --------------------------------------------------
- name: Push NRPE configuration file
  ansible.builtin.template:
      src: nrpe.cfg.j2
      dest: /etc/nagios/nrpe.cfg
      owner: root
      group: root
      mode: '0644'
  notify: Restart nrpe
  tags: nrpe_config

# --------------------------------------------------
# AJOUT CUSTOM SCRIPTs
# --------------------------------------------------
- name: Create custom-plugin repo if not created from previous tasks
  ansible.builtin.file:
      name: /usr/lib/nagios/custom-plugins
      state: directory
      owner: root
      group: root
      mode: '0755'

- name: Get custom scripts from gitlab
  ansible.builtin.git:
      repo: "https://sources.le-filament.com/lefilament/nagios-plugin.git"
      dest: "/usr/lib/nagios/custom-plugins"
      version: "master"
  when: inventory_hostname in groups.backup_server

- name: Set file rights on custom plugins
  ansible.builtin.file:
      name: "{{ item }}"
      mode: 0555
  with_items:
      - /usr/lib/nagios/custom-plugins/check_cloud_storage.sh
      - /usr/lib/nagios/custom-plugins/check_odoo_storage.sh
      - /usr/lib/nagios/custom-plugins/check_odoo2_storage.sh
  when: inventory_hostname in groups.backup_server

- name: Add check_mdstat script
  ansible.builtin.get_url:
      url: https://exchange.nagios.org/components/com_mtree/attachment.php?link_id=5423&cf_id=24
      dest: /usr/lib/nagios/custom-plugins/check_mdstat.sh
      mode: '0555'
  when: raid_config is defined

- name: Add extra scripts
  ansible.builtin.get_url:
      url: "{{ item.url }}"
      dest: /usr/lib/nagios/custom-plugins/{{ item.name }}
      mode: '0555'
  with_items: "{{ plugins_to_download }}"
  loop_control:
      label: "{{ item.name }}"

- name: Add nagios to www-data group
  ansible.builtin.user:
      name: nagios
      groups: www-data
      append: true
  when: inventory_hostname in groups.owncloud_server | union(groups.docker_owncloud) | union(groups.docker_nextcloud)

- name: Add cron job to update available packages every day
  ansible.builtin.cron:
      name: apt update
      minute: "42"
      hour: "7"
      job: /usr/bin/apt update
  when: inventory_hostname in groups.full_maintenance
